name: CI

on:
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run type-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: Run tests with coverage (thresholds commented out)
        run: |
          npm run test:ci
          # Uncomment the lines below when tests are in place
          # --coverage.thresholds.branches=80 \
          # --coverage.thresholds.functions=80 \
          # --coverage.thresholds.lines=80 \
          # --coverage.thresholds.statements=80
